name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Compile and Build
        run: yarn build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WebApp-Build
          path: ./dist
